### ISSUE TITLE
Fix the lobby invisibility bug

### ISSUE THREAD

**Issue by ghost** [HerpDerpinstine/DDSS.ModHelper#1]
Hi! I recently downloaded the helper mod.
I had to uninstall it as I don't see ANY lobbies.
Perhaps this is due to the fact that you can only see those who also have this mod.
Absolutely no lobbies are not there.
Fix it please!
By the way, at the beginning for a second only one lobby pops up, like there is your name.

- [x] Fix the massive bug with other lobbies being invisible and them not seeing yours.

**Comment by HerpDerpinstine** [comment]
The Mod Helper puts you into a Modded Matchmaking pool.
The game's Lobby Browser will only show you other public matches that are in the same pool as you.
